id: absTrigger
namespace: dev
tasks:
  - id: py
    type: io.kestra.core.tasks.scripts.Python
  - id: each
    type: io.kestra.core.tasks.flows.EachSequential
    tasks:
      - id: return
        type: io.kestra.core.tasks.debugs.Return
        format: "{{taskrun.value}}"
    value: "{{ trigger.blobs | jq('.[].uri') }}"

triggers:
  - id: watch
    type: io.kestra.plugin.azure.storage.blob.Trigger
    endpoint: "https://kestra.blob.core.windows.net"
    connectionString: "{{secret('AZURE_CONNECTION_STRING')}}"
    container: "stage"
    prefix: "marketplace/"
    action: MOVE
    moveTo:
      container: stage
      name: archive/marketplace/