id: singer
namespace: com.kestra.github

tasks:
  - id: list
    type: io.kestra.plugin.fs.http.Request
    headers:
      Accept: application/vnd.github+json
      Authorization: Bearer {{ namespace.github.token }}
      User-Agent: Kestra
    uri: https://api.github.com/orgs/kestra-io/repos?per_page=100
  - id: github
    type: io.kestra.plugin.singer.taps.GitHub
    accessToken: "{{ namespace.github.token }}"
    repositories: "{{ outputs.list.body | jq('.[].full_name') }}"
    startDate: "2019-07-01"
    streamsConfigurations:
      - replicationMethod: INCREMENTAL
        selected: true
      - selected: false
        stream: projects
      - selected: false
        stream: project_cards
      - selected: false
        stream: project_columns
      - selected: false
        stream: team_memberships
      - selected: false
    pipPackages:
      - tap-github==1.10.4
  - id: bigquery-target
    type: io.kestra.plugin.singer.targets.AdswerveBigQuery
    addMetadataColumns: true
    datasetId: github
    from: "{{ outputs.github.raw }}"
    location: EU
    projectId: "{{namespace.gcp.projectId}}"
    serviceAccount: "{{namespace.gcp.serviceAccount}}"

triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: 0 6 * * *
