id: yellow_taxi_data_backfill
namespace: dev
inputs:
  - name: monthYear
    type: STRING
    defaults: 2023-01

tasks:
  - id: downloadFromInputs
    type: io.kestra.plugin.fs.http.Download
    uri: https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_{{inputs.monthYear}}.parquet
    method: GET
    disabled: true

  - id: downloadBasedOnDate
    type: io.kestra.plugin.fs.http.Download
    uri: https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_{{schedule.date ?? execution.startDate | date("yyyy-MM")}}.parquet

  - id: shove_it_to_s3
    type: io.kestra.plugin.aws.s3.Upload
    from: "{{outputs.downloadFile.uri}}"
    key: yellow_taxi/raw/{{ schedule.date ?? execution.startDate | date("yyyy-MM") }}/yellow_taxi_{{ schedule.date ?? execution.startDate | date("yyyy-MM") }}.parquet'
    bucket: annageller
    region: eu-central-1
    accessKeyId: "{{secret('AWS_ACCESS_KEY_ID')}}"
    secretKeyId: "{{secret('AWS_SECRET_ACCESS_KEY')}}"

triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "0 8 1 * *"
    disabled: true
    backfill:
      start: 2023-01-01T00:00:00Z