id: snowflake_query_trigger
namespace: company.team

tasks:
  - id: each
    type: io.kestra.core.tasks.flows.ForEach
    values: "{{ trigger.rows }}"
    tasks:
      - id: welcome_message
        type: io.kestra.plugin.scripts.shell.Commands
        runner: PROCESS
        commands:
          - echo "{{ json(taskrun.value) }}"
          - echo "Welcome to Kestra {{ json(taskrun.value).FIRST_NAME }} {{ json(taskrun.value).LAST_NAME }}"

  - id: delete
    type: io.kestra.plugin.jdbc.snowflake.Query
    description: Delete rows to avoid double trigger
    sql: DELETE FROM KESTRA.PUBLIC.EMPLOYEES WHERE START_DATE >= '2023-08-01'
    # TRUNCATE TABLE KESTRA.PUBLIC.EMPLOYEES;

pluginDefaults:
  - type: io.kestra.plugin.jdbc.snowflake.Trigger
    values:
      url: jdbc:snowflake://<account-identifier>.snowflakecomputing.com?warehouse=DEMO
      username: "{{ secret('SNOWFLAKE_USERNAME') }}"
      password: "{{ secret('SNOWFLAKE_PASSWORD') }}"

  - type: io.kestra.plugin.jdbc.snowflake.Query
    values:
      url: jdbc:snowflake://<account-identifier>.snowflakecomputing.com?warehouse=DEMO
      username: "{{ secret('SNOWFLAKE_USERNAME') }}"
      password: "{{ secret('SNOWFLAKE_PASSWORD') }}"

triggers:
  - id: wait
    type: io.kestra.plugin.jdbc.snowflake.Trigger
    sql: "SELECT * FROM KESTRA.PUBLIC.EMPLOYEES WHERE START_DATE >= '2023-08-01';"
    interval: "PT5S"
    fetchType: FETCH
    disabled: false
