id: variables_in_trigger
namespace: company.team

inputs:
  - name: myinput
    type: STRING
    defaults: hello

variables:
  myvar: myvalue

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: hey "{{ inputs.myinput }}"

triggers:
  - id: minutely
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/1 * * * *"
    inputs:
      myinput: "{{ vars.myvar }}"
