id: webhookTrigger
namespace: prod
description: |
  To trigger that flow using `curl`:
  curl -X GET "http://localhost:8080/api/v1/executions/webhookTrigger/prod/webhook/ThisIsaSuperSecretKey42" -H "accept: text/json"
tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Hello from a flow triggered by a webhook
triggers:
  - id: webhook
    type: io.kestra.core.models.triggers.types.Webhook
    key: "{{envs.webhook_key}}"