# id: 10
# https://demo.kestra.io/ui/blueprints/community/10
# http://localhost:8080/ui/blueprints/10
# Schedule a flow every day at 6:30 AM
# Tags: Schedule, Variables
description: |
  This example shows how to schedule a flow at 6:30 AM every day.
  
  - If the flow is triggered manually, it will log the start date of the task. 
  - If the flow is triggered by a regular schedule, it will log the start date of the schedule trigger.
  
  The `date()` function formats the output to display hours and minutes. You can use that function to format the date based on your needs. 

id: 10_dailyFlow
namespace: blueprint

tasks:
  - id: log
    type: io.kestra.core.tasks.log.Log
    message: It's {{ trigger.date ?? taskrun.startDate | date("HH:mm") }}

triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "30 6 * * *"
