# id: 112
# https://demo.kestra.io/ui/blueprints/community/112
# http://localhost:8080/ui/blueprints/112
# Backfill a flow for Taxi Trip Data
# Tags: Backfills, Schedule, Variables
description: |
  To backfill a flow, add a `start` date from which Kestra should backfill the past runs before running the regular schedule.
  
  The expression `{{schedule.date ?? execution.startDate | date("yyyy-MM")}}` will always give you the execution date regardless of whether you triggered the flow ad-hoc or whether it ran based on a schedule. The date function formats the date according to the provided date template.

id: 112_taxiTripData
namespace: blueprint

tasks:
  - id: log
    type: io.kestra.core.tasks.log.Log
    message: running backfill for file https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_{{schedule.date ?? execution.startDate | date("yyyy-MM")}}.parquet

triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "0 8 1 * *" # at 8 AM on every first day of the month
    timezone: US/Eastern
    backfill:
      start: 2023-01-01T00:00:00Z
