# id: 37
# https://demo.kestra.io/ui/blueprints/community/37
# http://localhost:8080/ui/blueprints/37
# AWS S3 Event Trigger
# Tags: AWS, Trigger
description: |
  This flow will be triggered whenever new files with a given prefix are detected in the specified S3 bucket. It will download the files into the internal storage 
  and move the S3 objects to an `archive` folder (i.e. S3 object prefix with the name `archive`).
  
  The `EachParallel` task will iterate over the objects and print their URIs.
  
  It's recommended to set the `accessKeyId` and `secretKeyId` properties as secrets.

id: 37_s3Trigger
namespace: blueprint

tasks:
  - id: each
    type: io.kestra.core.tasks.flows.EachParallel
    tasks:
      - id: s3object
        type: io.kestra.core.tasks.debugs.Return
        format: "{{taskrun.value}}"
    value: "{{ trigger.objects | jq('.[].uri') }}"

triggers:
  - id: waitForS3object
    type: io.kestra.plugin.aws.s3.Trigger
    bucket: declarative-orchestration
    prefix: demo
    interval: PT1S
    filter: FILES
    action: MOVE
    moveTo:
      key: archive/demo/
    region: "{{ secret('AWS_DEFAULT_REGION') }}"
    accessKeyId: "{{ secret('AWS_ACCESS_KEY_ID') }}"
    secretKeyId: "{{ secret('AWS_SECRET_ACCESS_KEY') }}"
