# id: 45
# https://demo.kestra.io/ui/blueprints/community/45
# http://localhost:8080/ui/blueprints/45
# Parametrized workflow with multiple schedules
# Tags: Inputs, Schedule
description: |
  This flow takes a runtime-specific input and uses it to log a message to the console.
  The flow has two scheduled attached to it: 
  - one that runs every 15 minutes with the default input parameter value
  - another one that runs every 1 minute with a custom input parameter value
  
  Note that both schedules are currently disabled. 
  To start scheduling the flow, set the `disabled` property to `false` or delete that property entirely.

id: 45_parametrizedFlowWithMultipleSchedules
namespace: blueprint

inputs:
  - name: user
    type: STRING
    defaults: Data Engineer
    required: false

tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Hello {{ inputs.user }} from Kestra!

triggers:
  - id: quarterHourly
    type: io.kestra.core.models.triggers.types.Schedule
    disabled: true
    cron: "*/15 * * * *"
    inputs:
     name: user

  - id: everyMinute
    type: io.kestra.core.models.triggers.types.Schedule
    disabled: true
    cron: "*/1 * * * *"
    inputs:
     name: user
     value: custom value