# id: 48
# https://demo.kestra.io/ui/blueprints/community/48
# http://localhost:8080/ui/blueprints/48
# CI/CD to deploy Kestra flows using a GitHub webhook trigger
# Tags: Trigger Git
# TODO transfer ownership of this repo to kestra-io or move its contents to scripts
# TODO add info about basic auth to CLI as it got added
description: |
  This blueprint demonstrates how to use Kestra to build a CI/CD pipeline.
  
  This flow:
  - deploys other flows, effectively running a CI/CD pipeline for Kestra flows directly from Kestra itself
  - clones a GitHub repository, validates the flows, and then deploys them to a given Kestra namespace
  - uses a [webhook trigger](https://kestra.io/docs/developer-guide/triggers/webhook) so that the flow can be triggered upon GitHub push event sent by a GitHub webhook. 
  
  To learn more about this CI/CD pattern, check the following [documentation page](https://kestra.io/docs/developer-guide/cicd#deploy-flows-from-a-flow) and [blog post](https://levelup.gitconnected.com/when-github-actions-get-painful-to-troubleshoot-try-this-instead-9a134c9e9baf).

id: 48_ci-cd
namespace: blueprint

tasks:
  - id: deploy
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
      - id: cloneRepository
        type: io.kestra.plugin.git.Clone
        url: https://github.com/anna-geller/kestra-ci-cd # TODO
        branch: main

      - id: validateFlows
        type: io.kestra.plugin.scripts.shell.Commands
        runner: PROCESS
        commands:
          - /app/kestra flow validate flows/

      - id: deployFlows
        type: io.kestra.plugin.scripts.shell.Commands
        runner: PROCESS
        commands:
          - /app/kestra flow namespace update prod flows/prod/ --no-delete
          - /app/kestra flow namespace update prod.marketing flows/prod.marketing/ --no-delete

triggers:
  - id: github
    type: io.kestra.core.models.triggers.types.Webhook