id: api-to-s3
namespace: blueprint

tasks:
  - id: getPokemon
    type: io.kestra.plugin.fs.http.Download
    method: GET
    uri: https://pokeapi.co/api/v2/pokemon/psyduck

  - id: upload
    type: io.kestra.plugin.aws.s3.Upload
    bucket: kestraio
    from: "{{outputs.getPokemon.uri}}"
    key: psyduck.json
    accessKeyId: "{{ secret('AWS_ACCESS_KEY_ID') }}"
    secretKeyId: "{{ secret('AWS_SECRET_ACCESS_KEY') }}"
    region: "{{ secret('AWS_DEFAULT_REGION') }}"

triggers:
  - id: firstMondayOfTheMonth
    type: io.kestra.core.models.triggers.types.Schedule
    timezone: Europe/Berlin # adjust to your timezone
    cron: "0 17 * * FRI" # at 5 PM on every Friday
