id: aiven
namespace: blueprint

tasks:
  - id: cli
    type: io.kestra.plugin.scripts.python.Commands
    warningOnStdErr: false
    docker:
      image: python:slim
    beforeCommands:
      - pip install aiven-client
    commands:
      - avn --auth-token $AVN_AUTH_TOKEN project list
      - avn --auth-token $AVN_AUTH_TOKEN service update YOUR-SERVICE-NAME --power-off
      - avn --auth-token $AVN_AUTH_TOKEN service update YOUR-SERVICE-NAME --power-on
    env:
      AVN_AUTH_TOKEN: "{{ secret('AVN_AUTH_TOKEN') }}"

triggers:
  - id: every_morning
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "0 9 * * *"
