id: backfill_past_mondays
namespace: blueprint

tasks:
  - id: log_trigger_or_execution_date
    type: io.kestra.core.tasks.log.Log
    message: "{{ trigger.date ?? execution.startDate }}"

triggers:
  - id: firstMondayOfTheMonth
    type: io.kestra.core.models.triggers.types.Schedule
    timezone: Europe/Berlin
    backfill:
      start: 2023-04-01T00:00:00Z
    cron: "0 11 * * MON" # at 11 on every Monday
    scheduleConditions: # only first Monday of the month
      - type: io.kestra.core.models.conditions.types.DayWeekInMonthCondition
        date: "{{ trigger.date }}"
        dayOfWeek: "MONDAY"
        dayInMonth: "FIRST"
