id: hubspot_to_bigquery
namespace: blueprints

tasks:
  - id: sync
    type: io.kestra.plugin.cloudquery.Sync
    inputFiles:
      sa.json: "{{ secret('GCP_SERVICE_ACCOUNT') }}"
    env:
      GOOGLE_APPLICATION_CREDENTIALS: sa.json
      HUBSPOT_APP_TOKEN: "{{ secret('HUBSPOT_API_TOKEN') }}"
      CLOUDQUERY_API_KEY: "{{ secret('CLOUDQUERY_API_KEY') }}"
    configs:
      - kind: destination
        spec:
          name: bigquery
          path: cloudquery/bigquery
          registry: cloudquery
          version: "v3.3.16"
          write_mode: "append"
          spec:
            project_id: kestra-prd
            dataset_id: hubspot
      - kind: source
        spec:
          name: hubspot
          path: cloudquery/hubspot
          registry: cloudquery
          version: "v3.0.18"
          destinations:
            - "bigquery"
          tables:
            - "*"
          spec:
            max_requests_per_second: 5

triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: 0 6 * * *
