id: s3Trigger
namespace: blueprint

tasks:
  - id: each
    type: io.kestra.core.tasks.flows.EachParallel
    tasks:
      - id: s3object
        type: io.kestra.core.tasks.debugs.Return
        format: "{{taskrun.value}}"
    value: "{{ trigger.objects | jq('.[].uri') }}"

triggers:
  - id: waitForS3object
    type: io.kestra.plugin.aws.s3.Trigger
    bucket: declarative-orchestration
    prefix: demo
    interval: PT1S
    filter: FILES
    action: MOVE
    moveTo:
      key: archive/demo/
    region: "{{ secret('AWS_DEFAULT_REGION') }}"
    accessKeyId: "{{ secret('AWS_ACCESS_KEY_ID') }}"
    secretKeyId: "{{ secret('AWS_SECRET_ACCESS_KEY') }}"
