id: parametrizedFlowWithMultipleSchedules
namespace: blueprint

inputs:
  - name: user
    type: STRING
    defaults: Data Engineer
    required: false

tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Hello {{ inputs.user }} from Kestra!

triggers:
  - id: quarterHourly
    type: io.kestra.core.models.triggers.types.Schedule
    disabled: true
    cron: "*/15 * * * *"
    inputs:
      name: user

  - id: everyMinute
    type: io.kestra.core.models.triggers.types.Schedule
    disabled: true
    cron: "*/1 * * * *"
    inputs:
      name: user
      value: custom value
