id: ci-cd
namespace: blueprint

tasks:
  - id: deploy
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
      - id: cloneRepository
        type: io.kestra.plugin.git.Clone
        url: https://github.com/anna-geller/kestra-ci-cd
        branch: main

      - id: validateFlows
        type: io.kestra.plugin.scripts.shell.Commands
        runner: PROCESS
        commands:
          - /app/kestra flow validate flows/
      - id: deployFlows
        type: io.kestra.plugin.scripts.shell.Commands
        runner: PROCESS
        commands:
          - /app/kestra flow namespace update prod flows/prod/ --no-delete
          - /app/kestra flow namespace update prod.marketing flows/prod.marketing/
            --no-delete
triggers:
  - id: github
    type: io.kestra.core.models.triggers.types.Webhook
